logging:
  level:
    root: INFO
    oidc: DEBUG
    org.springframework.security: WARN

server:
  port: 8091
  error:
    path: /error

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"

config:
  client_url: http://localhost:3003
  server_login: http://localhost:8091/intake/api/sso

catalog:
  path: classpath:/catalog.yml

oidc:
  account_linking_context_class_ref: https://eduid.nl/trust/linked-institution

spring:
  security:
    oauth2:
      client:
        registration:
          oidc:
            client-id: student.mobility.rp.localhost
            client-secret: secret
            redirect-uri: http://localhost:8091/redirect_uri
            authorization-grant-type: authorization_code
        provider:
          oidc:
            authorization-uri: https://connect.test2.surfconext.nl/oidc/authorize
            token-uri: https://connect.test2.surfconext.nl/oidc/token
            user-info-uri: https://connect.test2.surfconext.nl/oidc/userinfo
            user-name-attribute: sub

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
    info:
      enabled: true
      show-details: when_authorized
