logging:
  level:
    root: INFO
    oidc: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8091
  servlet:
    session:
      cookie:
        secure: false

spring:
  jackson:
    default-property-inclusion: non_null

config:
  # Endpoint called by catalog. For testing purposes the client can call it as well
  start_broker_endpoint: http://localhost:8091/api/broker
  # Set to False in every non-local environment
  local: True
  # Do we allow to mock the different scenario's - only allow on test
  allow_playground: True
  # The basic authn to mimic the SIS that reports back results - only configure with values on test
  sis_user: sis
  sis_password: secret
  sis_results_endpoint: http://localhost:8092/api/play-results
  broker_client_url: http://localhost:3003
  oauth2:
    token_endpoint: http://localhost:8081/oidc/token
    client_id: student.mobility.broker.local
    secret: secret

service_registry:
  path: classpath:/service-registry.yml

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
