logging:
  level:
    root: INFO
    oidc: DEBUG
    org.springframework.security: DEBUG

server:
  port: 8091
  error:
    path: /error

config:
  # Set to False in every non-local environment
  local: True
  client_url: http://localhost:3003
  return_to: http://localhost:3003

service_registry:
  path: classpath:/service-registry.yml

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

# used by the git plugin
info:
  build:
    artifact: "@project.artifactId@"
    version: "@project.version@"
